-- Collaudo di 001_guard_history.sql su un Postgres LOCALE e vuoto (mai su produzione).
-- Uso: vedi tools/db/README.md. Stampa una riga per test; ogni riga deve finire con OK.
create table public.diary (id bigint generated by default as identity primary key, created_at timestamptz default now(), user_id text, data jsonb, updated_at timestamptz);
\i 001_guard_history.sql
\i 001_guard_history.sql
create temp table r(t text, ok boolean, detail text);
do $t$
declare base jsonb; id1 bigint; s int; c int; a int; n int; v text; ok boolean; lastmsg text;
begin
  base := (select jsonb_object_agg('k'||g, g) from generate_series(1,38) g)
          || jsonb_build_object('p2_day_1', jsonb_build_object('peso','72','hrv_min','20','hrv_max','60','rhr','55','ore_sonno','7'), 'p2_day_2', jsonb_build_object('peso','72'));
  insert into diary(user_id, data) values ('test', base) returning id into id1;

  update diary set data = jsonb_set(data, '{p2_day_1,peso}', '"72.4"') where id = id1;
  select count(*) filter (where kind='snapshot'), count(*) filter (where kind='change') into s, c from diary_history where diary_id = id1;
  insert into r values ('T1 modifica normale: 1 snapshot + 1 change', s=1 and c=1, s||'/'||c);

  update diary set data = jsonb_set(data, '{p2_day_1,rhr}', '"56"') where id = id1;
  select count(*) filter (where kind='snapshot'), count(*) filter (where kind='change') into s, c from diary_history where diary_id = id1;
  insert into r values ('T2 seconda scrittura stesso giorno: ancora 1 snapshot, 2 change', s=1 and c=2, s||'/'||c);

  select data->'p2_day_1'->>'peso' into v from diary_history where diary_id=id1 and kind='snapshot';
  insert into r values ('T3 lo snapshot contiene il valore PRIMA della scrittura (72)', v='72', v);

  select changes->'p2_day_1'->'old'->>'peso' || '->' || (changes->'p2_day_1'->'new'->>'peso') into v from diary_history where diary_id=id1 and kind='change' order by id limit 1;
  insert into r values ('T3b il change registra vecchio e nuovo (72->72.4)', v='72->72.4', v);

  update diary set data = jsonb_set(jsonb_set(jsonb_set(data,'{p2_day_1,peso}','"720"'),'{p2_day_1,rhr}','"abc"'),'{p2_day_1,hrv_min}','"90"') where id = id1;
  select count(*) into a from diary_anomalies where diary_id = id1;
  insert into r values ('T4 tre anomalie (fuori scala, non numerico, min>max)', a=3, a::text);

  update diary set data = jsonb_set(jsonb_set(jsonb_set(data,'{p2_day_1,peso}','"73,1"'),'{p2_day_1,rhr}','"58"'),'{p2_day_1,hrv_min}','"30"') where id = id1;
  select count(*) into n from diary_anomalies where diary_id = id1;
  insert into r values ('T5 valori normali (anche con virgola): nessuna nuova anomalia', n=3, n::text);

  select count(*) into c from diary_history where diary_id=id1 and kind='change';
  update diary set data = data where id = id1;
  select count(*) into n from diary_history where diary_id=id1 and kind='change';
  insert into r values ('T6 update senza cambiamenti: nessun nuovo change', c=n, c||'/'||n);

  begin update diary set data = data - 'k1' where id = id1; ok := true; exception when others then ok := false; end;
  insert into r values ('T7 perdita di 1 chiave su 40: consentita', ok, '');

  begin update diary set data = data - 'k2' - 'k3' - 'k4' where id = id1; ok := false; exception when others then ok := true; lastmsg := sqlerrm; end;
  insert into r values ('T8 perdita di 3 chiavi: bloccata', ok, lastmsg);

  begin update diary set data = null where id = id1; ok := false; exception when others then ok := true; end;
  insert into r values ('T9 data nullo: bloccato', ok, '');

  begin update diary set data = '{}'::jsonb where id = id1; ok := false; exception when others then ok := true; end;
  insert into r values ('T10 data vuoto {}: bloccato', ok, '');

  begin delete from diary where id = id1; ok := false; exception when others then ok := true; end;
  insert into r values ('T11a delete: bloccato', ok, '');
  begin truncate diary; ok := false; exception when others then ok := true; end;
  insert into r values ('T11b truncate: bloccato', ok, '');

  lastmsg := null;
  perform set_config('app.allow_destructive','on',true);
  begin update diary set data = data - 'k5' - 'k6' - 'k7' - 'k8' where id = id1; ok := true; exception when others then ok := false; lastmsg := sqlerrm; end;
  insert into r values ('T12a override: update distruttivo consentito', ok, coalesce(lastmsg,''));
  begin delete from diary where id = id1; ok := true; exception when others then ok := false; end;
  insert into r values ('T12b override: delete consentito', ok, '');
  perform set_config('app.allow_destructive','off',true);

  insert into diary(user_id, data) values ('t2', base) returning id into id1;
  begin delete from diary where id = id1; ok := false; exception when others then ok := true; end;
  insert into r values ('T13 dopo l''override il blocco e'' di nuovo attivo', ok, '');
end $t$;
select case when ok then 'OK     ' else 'FALLITO' end || ' ' || t || case when detail<>'' then '  [' || detail || ']' else '' end as esito from r;
select case when bool_and(ok) then 'TUTTI I TEST OK' else 'TEST FALLITI: ' || count(*) filter (where not ok) end from r;
